source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/MRGBB/specs.git'
use_frameworks!

target 'GBZSpecialKit_Example' do
  pod 'GBZSpecialKit', :path => '../'

  target 'GBZSpecialKit_Tests' do
    inherit! :search_paths

    
  end

end
